{% set name = "ujson" %}
{% set version = "5.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e204ae6f909f099ba6b6b942131cee359ddda2b6e4ea39c12eb8b991fe2010e0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
    - wheel
  run:
    - python

test:
  imports:
    - ujson
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v
  #downstreams:
  #  - anaconda-navigator 2.7.0
  #  - navigator-updater 0.6.0
  #  - python-lsp-server 1.13.1

about:
  home: https://github.com/ultrajson/ultrajson
  summary: Ultra fast JSON decoder and encoder written in C with Python bindings
  description: Ultra fast JSON decoder and encoder written in C with Python bindings
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/ultrajson/ultrajson/blob/main/README.md
  dev_url: https://github.com/ultrajson/ultrajson

extra:
  recipe-maintainers:
    - kszucs
    - synapticarbors
