travis:
  secure:
    BINSTAR_TOKEN: mxpWmA63/kk0MXkUG0uNVMjlyEEw+hHW3nEqufqjg7DLPOaEKOesc/iDhFSuYpYCOy18kaVepos/ik4W/6zTzwClyxJSb2avhb4jNA6GzpAmGB2ADvQ3pGvyRb3Ifmy5L05HAMjCvtLk7koLfQ6QI5uho1UXtEEncVbgI1aaZ4af8QRveX4iVl/aLWYXg/JYg73jDgChCLpmngX+KOEIUFEBAc0vR9w2So/qOQFWfZOkmMuTLavz0fVnwqPs2uGoo7Vbq0FhtDkSNkCsDuKqZiTLMhGjRLc3vu07RZI9TS6OgU2NCgGIxP21SnkFLBi8QCT82yACuf3t1JR5N1+ET8NbqIFzLBK97wi+4oaudsByUbz6YImspTu2/V35aoLJdzuhoeKT8gHYZ/kzAfJ07A6wmGEKHJsU3VGkc+XmsESmXNp6sDIe7iJlg1+ghwWXkZZnOw75lzVz/ev0y9AspptyceZLxfZjAjunv9jLzo3QTTYSfjrpUO8H/bJew7Z33WYfLnHb7cZBoPdwkyak7eDGHM6v6fd9dTjCuIv+3bWjrmO7aup7lyXo2LAdMaWlIq8ULy+K9mLUAzVMnwOk8GVT6P9AL/QjcCPSSK14Ul3ffS18TjQhJkWBZ+HWazMJbRCoy6+0h0RTOVpKWWsJbeYaDJNXRg34zgTB+8YNoJA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
